# Generated by Django 6.0.2 on 2026-02-16 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendox', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentCreator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('expertise', models.CharField(blank=True, help_text='e.g., Movie Reviewer, Series Expert', max_length=200, null=True)),
                ('total_contents_added', models.IntegerField(default=0)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creator_profile', to='recommendox.userprofile')),
            ],
            options={
                'permissions': [('can_manage_content', 'Can add, edit, delete content')],
            },
        ),
    ]
