# Generated by Django 6.0.2 on 2026-02-17 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendox', '0002_contentcreator'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
